### ISSUE TITLE
Sound output wrong position

### ISSUE THREAD

**Issue by sedax90** [Rayzeq/quick-settings-audio-panel#3] opened 2023-05-03 14:44 UTC
When I expand the output panel, it expands down correctly, but the new audio output panel incorrectly overlaps everything else in the panel and doesn't move other items down (Ubuntu 23.04)

![image](https://user-images.githubusercontent.com/5001801/235950692-23889351-5d6a-4352-8556-35a039dca8b2.png)

**Comment by Rayzeq** [comment] 2023-05-04 06:10
Thanks for reporting this bug!
Unfortunately I can't fix it with the current way the extension works, I'll fix it but it may take some time because I need to rewrite a good part of the extension

**Comment by Rayzeq** [comment] 2023-05-07 00:23
Until I make a proper fix, I made a quick fix in version 8 of the extension, it's an option called "Overlay popups". Note that this will affect all popups in the quick settings.

**Comment by conradson** [comment] 2023-05-07 08:38
I can confirm that the quick fix works (and affect all popups). Thanks.

**Comment by Rayzeq** [comment] 2023-07-07 20:24
This issue has been fixed in the latest version, which won't be available straight away because it has to pass the review.

**Closed by Rayzeq** 2023-07-07 20:24 UTC
