### ISSUE TITLE
Disable the scrim?

### ISSUE THREAD

**Issue by sbeve72** [Rayzeq/quick-settings-audio-panel#23] opened 2023-09-30 05:20 UTC
This extensions adds a background scrim when the quick panel is opened. I want to disable that.

**Comment by Rayzeq** [comment] 2023-09-30 14:42
There shouldn't be any background scrim. Could you send a screenshot of it ?
The issue is probably caused by an extension that adds custom CSS, so it would also help to send the list of extensions you have installed.

**Comment by sbeve72** [comment] 2023-09-30 17:03
It happens when the User Themes extension is enabled along with this extension. But it doesn't happen with other extensions enabled including QSTweaks.

**Comment by sbeve72** [comment] 2023-09-30 17:05
$ gnome-extensions list 
bluetooth-quick-connect@bjarosze.gmail.com
quick-settings-tweaks@qwreey
noannoyance-fork@vrba.dev
dash-to-dock@micxgx.gmail.com
user-theme@gnome-shell-extensions.gcampax.github.com
gsconnect@andyholmes.github.io
AlphabeticalAppGrid@stuarthayhurst
custom-hot-corners-extended@G-dH.github.com
gnome-ui-tune@itstime.tech
display-brightness-ddcutil@themightydeity.github.com
activities-filled-pill@verdre
clipboard-indicator@tudmotu.com
app-hider@lynith.dev
trayIconsReloaded@selfmade.pl

**Comment by sbeve72** [comment] 2023-09-30 17:06
Besides this, when this extension is enabled, clicking on the 'Power Menu' icon from the Quick Settings Panel (aka User Panel) and opening the overlay that appears after clicking it overlaps other icons. Doesn't happen with any other extensions installed.

**Comment by Rayzeq** [comment] 2023-09-30 17:15
OK, that confirms that the issue is with the custom CSS. Could you tell me which theme you're using? I only have Yaru (and its colour variants) and there is no issue with it.
It is normal that the issue does not occur with QSTweaks, because my extension modifies the panel much more than QSTweaks does.
The issue with the power menu is probably also due to an incompatibility between the theme you're using and my extension (unless it also happens when User Themes is disabled ?).

**Comment by sbeve72** [comment] 2023-09-30 19:54
I am using [Catppuccin Mocha for GTK](https://github.com/catppuccin/gtk). And yes the second error occurs even with all extensions disabled except this one.

**Comment by Rayzeq** [comment] 2023-09-30 20:49
Strange, the only issue I have with this theme is that the panels are not themed when dragged.
I'm beginning to suspect that I've misunderstood the word "scrim", I'm french and deepl translates it as the french word for "grid".
Do you mean by "scrim" the darkening of the background?
About the power menu, I don't really know what could be the issue, could you post a screenshot of the thing when it's broken ?

**Comment by Rayzeq** [comment] 2023-09-30 20:51
Uh, I just realized that the background isn't supposed to darken anyway, I'll look into the issue

**Comment by Rayzeq** [comment] 2023-09-30 22:23
It's now fixed in version 23, which is pending review.

**Closed by Rayzeq** 2023-09-30 22:23 UTC

**Comment by Rayzeq** [comment] 2023-09-30 22:27
Also, could you open a new issue with a screenshot for the second issue ?

**Comment by sbeve72** [comment] 2023-10-01 06:26
Sure, I will do that. And yes, thats what i meant by scrim.
